name: Devops Workflow 

on:
  push:
    branches:
      -main

jobs:
  build:
    runs:on: ubunto-latest 

    steps: 
      - name: checkout de codigo      
        uses: action/checkout@v4

      - name: mostrar mensagem
        run: echo "Ola, mundo Devops"   
      